config/routes.rb
Rails.application.routes.draw do



  resource :session, only: [:new, :create, :destroy]

  resources :departaments
  resources :users
  resources :feedbacks
  get "user_feedback_list/:user_id" => "feedbacks#user_feedback_list", as: "user_feedback_list"

  root "sessions#new"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/departament.rb
class Departament < ApplicationRecord

  belongs_to :user

  has_many :user_departaments
  has_many :users, through: :user_departaments


end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :user

  QUESTIONS = [
    "Planejamento e organização: Como você avalia a clareza dos objetivos, o planejamento das atividades e a organização dos recursos?",
    "Eficiência dos processos: Os processos são executados de forma eficiente, sem desperdícios e com foco em resultados?",
    "Utilização de recursos: Os recursos (materiais, equipamentos, pessoas) são utilizados de forma otimizada e responsável?",
    "Qualidade dos produtos/serviços: Os produtos ou serviços entregues atendem aos padrões de qualidade e às expectativas dos clientes?",
    "Melhoria contínua: A empresa busca constantemente aprimorar seus processos e resultados, incentivando a participação de todos?",
    "Comunicação interna: A comunicação entre as áreas e os colaboradores é clara, eficiente e transparente?",
    "Resolução de problemas: Os problemas são identificados e resolvidos de forma rápida e eficaz, com foco em soluções preventivas?",
    "Cultura de excelência: A empresa promove uma cultura de busca pela excelência, valorizando a disciplina, o profissionalismo e o aprendizado?"
  ]

  def formatted_created_at
    created_at.strftime("%d/%m/%Y")
  end




end

app/models/user.rb
class User < ApplicationRecord


  before_save :set_name, :set_username, :set_email
  has_many :user_departaments
  has_many :departaments, through: :user_departaments
  has_many :feedbacks

  validates :job_grade, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 11 }

  JOB_GRADE = 1..11


  private
  def set_name
    self.name = self.first_name.downcase + " " + self.last_name.downcase
  end
  def set_username
    self.username = self.name.gsub(" ", "_")
  end

  def set_email
    self.email = self.username + "@vitu.com"
  end


end

app/models/user_departament.rb
class UserDepartament < ApplicationRecord
  belongs_to :user
  belongs_to :departament
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base





  private
  def set_manager_list
    @managers = User.where('job_grade <= ?', 5)
  end

  def current_user
    @current_user ||= User.find(session[:manager_id]) if session[:manager_id]
  end

  def require_signin
    unless current_user
      session[:intended_url] = request.url
      redirect_to new_session_url, alert: "Please sign in."
    end
  end





  helper_method :current_user
  helper_method :is_your_user

end

app/controllers/departaments_controller.rb
class DepartamentsController < ApplicationController

  before_action :require_signin
  before_action :set_manager_list
  before_action :set_departament , only: [:show, :edit, :update, :destroy]

  def index
    @departament = Departament.all
  end

  def new
    @departament = Departament.new
  end

  def create
    @departament = Departament.new(set_departament_params)

    if @departament.save
      redirect_to "/"
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def show

  end

  def edit

  end

  def update
    if @departament.update(set_departament_params)
      redirect_to "/"
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    fail
  end

  private
  def set_departament_params
    params.require(:departament).permit(:name, :user_id)
  end

  def set_departament
    @departament = Departament.find(params[:id])
  end

end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController

  before_action :require_signin
  before_action :is_your_user?, only: [:user_feedback_list]
  before_action :set_feedback_columns, only: [:new, :create]
  before_action :set_question_array, only: [:new, :create]
  before_action :set_user_to_feedback, only: [:new, :user_feedback_list]


  def index
    @usersFeedback = User.where('manager_id == ?', current_user.id)
  end

  def show

  end

  def new
    @feedback = Feedback.new

  end

  def create
    @feedback = Feedback.new(set_feedback_params)
    @feedback.manager_id = current_user.id
    if @feedback.save
      redirect_to feedbacks_url, notice: 'Feedback was successfully created.'
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def user_feedback_list
    @feedbacks = Feedback.where(user_id: params[:user_id])



  end

  private
  def set_feedback_params
    params.require(:feedback).permit(
      :nota_1,
      :nota_2,
      :nota_3,
      :nota_4,
      :nota_5,
      :nota_6,
      :nota_7,
      :nota_8,
      :comments,
      :user_id,
      :manager_id,
    )
  end

  def set_feedback_columns
    @feedbackColumns = Feedback.column_names.select { |column| column.start_with?("nota_")}
  end

  def set_question_array
    @questions = Feedback::QUESTIONS.each
  end

  def set_user_to_feedback
    @user = User.find(params[:user_id])
  end

  def is_your_user?
    unless User.where(manager_id: current_user.id).where(id: params[:user_id]).exists?
      redirect_to feedbacks_url, notice: 'You are not allowed to view this page'
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.email.eql?("victor_wentz@vitu.com")
      session[:manager_id] = user.id
      redirect_to users_url, notice: "welcome back"
    elsif user && user.job_grade <= 6
      session[:manager_id] = user.id
      redirect_to feedbacks_url, notice: "welcome back"
    else
      render :new, status: :unprocessable_entity

    end
  end

  def destroy
    session[:manager_id] = nil
    redirect_to root_url, status: :see_other
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :require_signin
  before_action :set_manager_list
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
    # set_user
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(set_user_params)

    if @user.save
      redirect_to "/"
    else
      render 'new', status: :unprocessable_entity
    end

  end

  def edit
    # set_user

  end

  def update
    # set_user
    if @user.update(set_user_params)
      redirect_to "/"
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    fail
  end

  private
  def set_user_params
    params.require(:user).permit(:first_name, :last_name, :manager_id, :job_grade, departament_ids: [])
  end

  def set_user
    @user = User.find(params[:id])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find(session[:manager_id]) if session[:manager_id]
  end

  def route_page?
    request.path.eql?(root_path)
  end
end

app/helpers/departaments_helper.rb
module DepartamentsHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/departaments/_forms.html.erb
<%=form_with(model: object) do |f| %>

  <%=f.label "Nome do departamento" %>
  <%=f.text_field :name %>

  <%= f.label "Gestor Responsavel" %>
  <%= f.collection_select :user_id, @managers, :id, :name, prompt: "Selecione um gerente" %>


  <% if object.new_record? %>
    <%= f.submit "Criar departamento" %>
  <% else %>
    <%= f.submit "Editar departamento" %>
  <% end %>

<% end %>

app/views/departaments/edit.html.erb
<section>
  <h1>
    Editar: <%=@departament.name %>
  </h1>
  <%=render "forms", object: @departament %>
</section>

app/views/departaments/index.html.erb
<section>
  <h1>
    Lista de Departamentos
  </h1>
  <%@departament.each do |dep| %>
    <%=link_to dep.name, dep %>
    <br>
  <% end %>
</section>

app/views/departaments/new.html.erb
<section>
  <h1>
    Criar Novo Departamento
  </h1>
  <%=render "forms", object: @departament %>
</section>

app/views/departaments/show.html.erb
<section>
  <h1>
    Departamento: <%=@departament.name %>
  </h1>
  <div class = 'departament-details'>
    <p>
      Gestor: <%=link_to @departament.user.name.capitalize, @departament.user %>
    </p>
    <div>
      <%=link_to "Editar Departamento", edit_departament_path %>
    </div>
    <h4>
      Funcionarios do departamento
    </h4>
    <table>
      <thead>
      <tr>
        <th>Nome</th>
        <th>Função</th>
        <th>Grade</th>
        <th>Email</th>
        <th>Data de Contratação</th>
      </tr>
      </thead>
      <tbody>
      <% @departament.users.each do |user| %>
        <tr>
          <td><%=link_to user.name, user %></td>
          <td>Placeholder</td>
          <td><%= user.job_grade %></td>
          <td><%= user.email %></td>
          <td><%= user.created_at.strftime("%d/%m/%Y %H:%M") %></td>
        </tr>
      <% end %>
      </tbody>
    </table>

  </div>
</section>

app/views/feedbacks/index.html.erb
<section>
  <table>
    <thead>
    <tr>
      <th>Nome</th>
      <th>Função</th>
      <th>Departamento</th>
      <th>Ultimos feedbacks</th>
      <th>Novo Feedback</th>
      <th>Quantidade</th>
    </tr>
    </thead>
    <tbody>
    <% @usersFeedback.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td>"Placeholder"</td>
        <td><%= user.departaments.first.name%></td>
        <td><%=button_to "feedbacks lista", user_feedback_list_path(user_id: user.id), method: :get  %></td>
        <td><%=link_to "novo feedback", new_feedback_path(user_id: user.id) %></td>
        <td><%=user.feedbacks.size %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</section>

app/views/feedbacks/new.html.erb
<%=form_with(model: @feedback) do |f| %>
  <%= f.hidden_field :user_id, value: @user.id %>
  <% @feedbackColumns.each do |column| %>
    <%= f.label @questions.next %>
    <% (0..10).each do |opcao| %>
      <div>
        <%= f.radio_button column, opcao %>
        <%= f.label column, opcao %>
      </div>
    <% end %>
    <br>
  <% end %>
  <%=f.label "Comentarios Finais" %><br>
  <%=f.text_field :comments %>
  <br>
  <%=f.submit "Enviar feedback" %>
<% end %>

app/views/feedbacks/user_feedback_list.html.erb
<h1> Lista de feedbacks de <%=@user.name %></h1>

<% if not @user.feedbacks.empty? %>
  <table>
    <thead>
    <tr>
      <th>Data feedback</th>
      <th>p1</th>
      <th>p2</th>
      <th>p3</th>
      <th>p4</th>
      <th>p5</th>
      <th>p6</th>
      <th>p7</th>
      <th>p8</th>
      <th>Comentarios</th>
    </tr>
    </thead>
    <tbody>
    <% @user.feedbacks.each do |feed| %>
      <tr>
        <td><%= feed.formatted_created_at %></td>
        <td><%= feed.nota_1 %></td>
        <td><%= feed.nota_2 %></td>
        <td><%= feed.nota_3 %></td>
        <td><%= feed.nota_4 %></td>
        <td><%= feed.nota_5 %></td>
        <td><%= feed.nota_6 %></td>
        <td><%= feed.nota_7 %></td>
        <td><%= feed.nota_8 %></td>
        <td><%= feed.comments %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <%else %>
  sem feed
<%end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Employees Feedback</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
<!--    <script src="https://cdn.tailwindcss.com"></script>-->
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />

  </head>

  <body>

    <% if not route_page? %>
      <%=render "layouts/partials/header" %>
    <% end %>
    <main>

      <%=yield %>
    </main>


  </body>
  <%#=render "layouts/partials/footer" %>
</html>

app/views/layouts/partials/_footer.html.erb
<footer>
  <p>
    Created by: <a href="https://www.linkedin.com/in/victor-wentz/">Victor Wentz</a>
  </p>
</footer>

app/views/layouts/partials/_header.html.erb
<nav id="sidebar">
  <div id="sidebar_content">
    <div class="user">
      <%=image_tag "man.jpg", id:"user_avatar", alt:"Avatar" %>
      <p id='user_infos'>
        <% if current_user %>
          <span class="item-description">
            <%=current_user.name %>
          </span>
          <span class="item-description">
          <%=current_user.job_grade %>
          </span>
        <% end %>
      </p>
    </div>

    <ul id="side_items">
      <li class="side-item">
        <a>
          <i class="fa-regular fa-paste"></i>
          <span class="item-description">
          <%=link_to "Feedbacks", feedbacks_url   %>
        </span>
        </a>
      </li>
      <% if current_user && current_user.email.eql?("victor_wentz@vitu.com") %>
        <li class="side-item">
          <a>
            <i class="fa-solid fa-user"></i>
            <span class="item-description">
          <%= link_to "Funcionarios", users_url %>
          </span>
          </a>
        </li>
        <li class="side-item">
          <a>
            <i class="fa-solid fa-house"></i>
            <span class="item-description">
          <%= link_to "Departamentos", departaments_url %>
          </span>
          </a>
        </li>
      <% end %>
    </ul>
    <button id="open_btn">
      <i id='open_btn_icon' class = 'fa-solid fa-chevron-right'></i>
    </button>
    <div id="logout">
      <%= button_to session_path, method: :delete, class: "logout-btn" do %>
        <i class="fa-solid fa-right-from-bracket"></i> Sign Out
      <% end %>
    </div>


  </div>
</nav>

app/views/users/_forms.html.erb
<%= form_with(model: object) do |f|  %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name, autofocus:true %>

  <%= f.label :last_name %>
  <%= f.text_field :last_name %>

  <%= f.label "Manager" %>
  <%= f.collection_select :manager_id, @managers, :id, :name, prompt: "Selecione um gerente" %>

  <%= f.label :job_grade %>
  <%= f.select :job_grade, User::JOB_GRADE.to_a, prompt: "Selecione um Grade!" %>

  <%= f.label "Departamentos" %>
  <%= f.collection_check_boxes :departament_ids, Departament.all, :id, :name %>

  <%=f.submit %>

<% end %>

app/views/users/edit.html.erb
<section>

  <h1> Editar: <%=@user.name %></h1>

  <%=render "forms", object: @user %>
</section>

app/views/users/index.html.erb
<section>
  <%=link_to "Criar usuario", new_user_path %>
  <%=link_to "Criar Departamento", new_departament_path %>
</section>
<section>
  <h1>
    Quantidade de Departamentos:
  </h1>
  <% @managers.each do |user| %>
    <span>
      <%= user.name %> : <%=user.departaments.size %>, <%=user.departaments.pluck(:name) %>
    </span>
    <br>
  <% end %>
</section>
<section>
  <h1>
    Lista Funcionarios
  </h1>
  <% @users.each do |user| %>
    <%=link_to user.name, user %>
    <br>
  <% end %>
</section>

app/views/users/new.html.erb
<%= form_with(model: @user) do |f|  %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name, autofocus:true %>

  <%= f.label :last_name %>
  <%= f.text_field :last_name %>

  <%= f.label "Manager" %>
  <%= f.collection_select :manager_id, @managers, :id, :name, prompt: "Selecione um gerente" %>

  <%= f.label :job_grade %>
  <%= f.select :job_grade, User::JOB_GRADE.to_a, prompt: "Selecione um Grade!" %>

  <%=f.submit %>

<% end %>

app/views/users/show.html.erb
<section>
  <h1>
    Perfil de: <%=@user.name.capitalize %>
  </h1>

  <%=link_to "Editar usuario", edit_user_path %>

</section>